In [28]:
# Taha Workspace
import pandas as pd
import sqlite3
import requests
import numpy

API_key = 'https://api.restcountries.com/countries/v5?response_fields=names.common,borders,currencies&limit=100'

headers = {
    "Authorization": f"Bearer rc_live_c3badbed198e4610b8cc7f0abc9f7401"
}

response = requests.get(API_key, headers=headers)
if response.status_code == 200:
    data = response.json()
else:
    print(f"Error: {response.status_code} - {response.text}")
    

df = pd.DataFrame(data['data']['objects'])  

df['name'] = df['names'].str['common']
df['currency'] = df['currencies'].str[0].str['name']
df = df[['name', 'currency', 'borders']]
df['borders'] = df['borders'].str.join(', ')

df['borders'] = df['borders'].replace('', 'ISLAND')

df

,name,currency,borders
0,Abkhazia,Russian ruble,"GEO, RUS"
1,Afghanistan,Afghan afghani,"IRN, PAK, TKM, UZB, TJK, CHN"
2,Albania,Albanian lek,"MNE, GRC, MKD, UNK"
3,Algeria,Algerian dinar,"TUN, LBY, NER, ESH, MRT, MLI, MAR"
4,American Samoa,United States dollar,ISLAND
...,...,...,...
95,Guyana,Guyanese dollar,"BRA, SUR, VEN"
96,Haiti,Haitian gourde,DOM
97,Heard Island and McDonald Islands,NaN,ISLAND
98,Honduras,Honduran lempira,"GTM, SLV, NIC"
99,Hong Kong,Hong Kong dollar,CHN

In [ ]:
# Rawad Workspace
import pandas as pd
import sqlite3
import requests
import numpy

API_key = 'https://api.restcountries.com/countries/v5?response_fields=population,region,languages&limit=100'

headers = {
    "Authorization": f"Bearer rc_live_c3badbed198e4610b8cc7f0abc9f7401"
}

response = requests.get(API_key, headers=headers)
if response.status_code == 200:
    data = response.json()
else:
    print(f"Error: {response.status_code} - {response.text}")
    

df = pd.DataFrame(data['data']['objects'])  
df

,region,languages,population,_meta
0,Asia,"[{'bcp47': 'ab', 'iso639_1': 'ab', 'iso639_2b'...",244236,{'lastUpdatedTimestamp': 1788557516}
1,Asia,"[{'bcp47': 'prs', 'iso639_1': '', 'iso639_2b':...",43844000,{'lastUpdatedTimestamp': 1788724017}
2,Europe,"[{'bcp47': 'sq', 'iso639_1': 'sq', 'iso639_2b'...",2335930,{'lastUpdatedTimestamp': 1788557516}
3,Africa,"[{'bcp47': 'ar', 'iso639_1': 'ar', 'iso639_2b'...",47400000,{'lastUpdatedTimestamp': 1788557516}
4,Oceania,"[{'bcp47': 'en', 'iso639_1': 'en', 'iso639_2b'...",43268,{'lastUpdatedTimestamp': 1788724017}
...,...,...,...,...
95,Americas,"[{'bcp47': 'en', 'iso639_1': 'en', 'iso639_2b'...",956044,{'lastUpdatedTimestamp': 1792354394}
96,Americas,"[{'bcp47': 'fr', 'iso639_1': 'fr', 'iso639_2b'...",11867032,{'lastUpdatedTimestamp': 1788557518}
97,Antarctic,"[{'bcp47': 'en', 'iso639_1': 'en', 'iso639_2b'...",0,{'lastUpdatedTimestamp': 1788724018}
98,Americas,"[{'bcp47': 'es', 'iso639_1': 'es', 'iso639_2b'...",10186738,{'lastUpdatedTimestamp': 1788557518}
99,Asia,"[{'bcp47': 'en', 'iso639_1': 'en', 'iso639_2b'...",7498100,{'lastUpdatedTimestamp': 1788724018}

In [ ]:
# Mohammad Workspace
import pandas as pd
import sqlite3
import requests
import numpy

API_key = 'https://api.restcountries.com/countries/v5?response_fields=economy,area,coordinates&limit=100'

headers = {
    "Authorization": f"Bearer rc_live_c3badbed198e4610b8cc7f0abc9f7401"
}

response = requests.get(API_key, headers=headers)
if response.status_code == 200:
    data = response.json()
else:
    print(f"Error: {response.status_code} - {response.text}")
    

df = pd.DataFrame(data['data']['objects'])  
df

,area,coordinates,economy,_meta
0,"{'kilometers': 8665, 'miles': 3345.6}","{'lat': 43, 'lng': 41}",{'gini_coefficient': {}},{'lastUpdatedTimestamp': 1788557516}
1,"{'kilometers': 652230, 'miles': 251827.3}","{'lat': 33, 'lng': 65}",{'gini_coefficient': {}},{'lastUpdatedTimestamp': 1788724017}
2,"{'kilometers': 28748, 'miles': 11099.7}","{'lat': 41, 'lng': 20}","{'gini_coefficient': {'2016': 33.7, '2017': 33...",{'lastUpdatedTimestamp': 1788557516}
3,"{'kilometers': 2381741, 'miles': 919595}","{'lat': 28, 'lng': 3}","{'gini_coefficient': {'1988': 37.4, '1995': 35...",{'lastUpdatedTimestamp': 1788557516}
4,"{'kilometers': 199, 'miles': 76.8}","{'lat': -14.33333333, 'lng': -170}",{'gini_coefficient': {}},{'lastUpdatedTimestamp': 1788724017}
...,...,...,...,...
95,"{'kilometers': 214969, 'miles': 83000}","{'lat': 5, 'lng': -59}","{'gini_coefficient': {'1992': 39.5, '1998': 45...",{'lastUpdatedTimestamp': 1792354394}
96,"{'kilometers': 27750, 'miles': 10714.3}","{'lat': 19, 'lng': -72.41666666}","{'gini_coefficient': {'2001': 59, '2012': 41.1}}",{'lastUpdatedTimestamp': 1788557518}
97,"{'kilometers': 412, 'miles': 159.1}","{'lat': -53.0818, 'lng': 73.5042}",{'gini_coefficient': {}},{'lastUpdatedTimestamp': 1788724018}
98,"{'kilometers': 112492, 'miles': 43433.4}","{'lat': 15, 'lng': -86.5}","{'gini_coefficient': {'2017': 49.4, '2018': 48...",{'lastUpdatedTimestamp': 1788557518}
99,"{'kilometers': 1104, 'miles': 426.3}","{'lat': 22.267, 'lng': 114.188}",{'gini_coefficient': {}},{'lastUpdatedTimestamp': 1788724018}